name: 'Bancolombia Toolkit InnerSource-OpenSource'
description: 'Action that provides repositories with the necessary tools and documentation for an innersource work model'
branding:
  icon: 'check-square'
  color: 'white'
inputs:
  GH_TOKEN:  #ID de token GitHub
    description: 'Token GitHub'
    required: true
  TYPE_REPOSITORY:  
    description: 'Repository type opensource or innersource'
    required: true
  USERS_REVIEWERS:  
    description: 'Issue Reviewers separated by space'
    required: true
runs:
  using: "composite"
  steps:
    - run: |
           echo "${{ github.action_path }}" >> $GITHUB_PATH
      shell: bash
    - name: add labels
      env:
          GH_TOKEN: ${{ inputs.GH_TOKEN }}
      run: addlabels.sh
      shell: bash
    - name: add issues templates
      env:
        GH_TOKEN: ${{ inputs.GH_TOKEN }}
      run: addissuestemplates.sh
      shell: bash
    - name: add workflows templates
      env:
        GH_TOKEN: ${{ inputs.GH_TOKEN }}
      run: addworkflowstemplates.sh
      shell: bash
    - name: add documentation templates
      env:
        GH_TOKEN: ${{ inputs.GH_TOKEN }}
      run: adddocumentationtemplates.sh
      shell: bash
    - name: push changues
      env:
        GH_TOKEN: ${{ inputs.GH_TOKEN }}
      run: uploadchangues.sh
      shell: bash
