name: 'Bancolombia Toolkit InnerSource-OpenSource'
description: 'Action that provides repositories with the necessary tools and documentation for an innersource work model'
branding:
  icon: 'check-square'
  color: 'white'
inputs:
  GH_TOKEN:  #ID de token GitHub
    description: 'Token GitHub'
    required: true
  TYPE_REPOSITORY:  
    description: 'Repository type opensource or innersource'
    required: true
  USERS_REVIEWERS:  
    description: 'Issue Reviewers separated by space'
    required: true
  TEMPLATE_LANGUAGE:  
    description: 'Language of templates ES (spanish) or EN (english)'
    required: true
runs:
  using: "composite"
  steps:
    - run: |
           echo "${{ github.action_path }}" >> $GITHUB_PATH
      shell: bash
    - name: install templates and workflows
      env:
        GH_TOKEN: ${{ inputs.GH_TOKEN }}
        VAR_USERS_REVIEWERS: ${{ inputs.USERS_REVIEWERS }}
        VAR_TEMPLATE_LANGUAGE: ${{ inputs.TEMPLATE_LANGUAGE }}
        VAR_TYPE_REPOSITORY: ${{ inputs.TYPE_REPOSITORY }}
      run: scriptsinstalltemplates.sh
      shell: bash